### ISSUE TITLE
:react doesn't recognise punctuation

### ISSUE THREAD

**Issue by teamshortcut** [CyberDiscovery/cyberdisc-bot#129]
The :react command doesn't recognise punctuation such as ? and ! (Which have associated emojis) For example, :react Test? Will only react with "Test", not the question mark. This seems an easy enough issue to fix?

**Comment by thebeanogamer** [comment]
Are there emoji for punctuation other than `?` and `!`?

**Comment by teamshortcut** [comment]
:grey_exclamation: :exclamation: :grey_question: :question: :bangbang: :interrobang: :heavy_dollar_sign:

**Comment by joker314** [comment]
Thanks for the list @teamshortcut . I reviewed each one and have confirmed that they all work in Discord. In addition, I discovered an additional emoji: :heavy_heart_exclamation: . 

I think we could include it at the lowest precedence, so that if we use up all the other exclamation emoji we can resort to it.
