### ISSUE TITLE
Significant lag during automatic reactions

### ISSUE THREAD

**Issue by AnonGuy** [CyberDiscovery/cyberdisc-bot#199]
Because we aren't cancelling any of the automatic reactions once one's been triggered, it's possible to cause considerable lag for the bot by just sending a few messages:

![image](https://user-images.githubusercontent.com/25161069/56440195-a01d9380-62e0-11e9-98c2-eaca0213a98d.png)

**Comment by jos-b** [comment]
Maybe we could add a discord.py cool down to the react command? It feels like something which could easily clutter a channel anyway so maybe we should try to reduce the invocations.

We could go for something like it can be used twice per minute per channel or maybe once per minute per user depending on how frequently we want it to be used.

**Comment by jos-b** [comment]
Should we decide a cool down on the command would be appropriate I'd be happy to implement 👍

**Comment by jos-b** [comment]
Also, maybe just restrict auto-reaction to the first token detected in the message? @thebeanogamer what do you think?

**Comment by thebeanogamer** [comment]
I don't have too much of a preference regarding time, but only doing the first one detected would probably be a good idea. It will require us to set a hierarchy of reactions though.

**Comment by jos-b** [comment]
Not necessarily, we could just change the auto-reaction system to scan through a message and just whatever trigger is found first we react to that.

**Comment by jos-b** [comment]
I think a rate limit might be a good idea, because it can get messy, just imagine the stuff in the screenshot happening in #general or whatever.

**Comment by thebeanogamer** [comment]
👍 Those both seem good to me

**Comment by jos-b** [comment]
I'll open a PR after lunch to restrict to 1 auto-reaction per message and maybe add a rate limit depending on the general consensus here.

**Comment by picapi** [comment]
Although ratelimits in Discord can vary, I believe for reactions it is roughly 0.25 seconds, meaning roughly 4 reactions can be sent in a second.

A cooldown for the :react command is definitely not a bad idea, but it may not resolve the issue pictured, which is slow reactions for auto-react key words. Right now, due to the asynchronous nature of events, each reaction will resolve in a semi-random order; it may be possible to tweak some things so they occur in chronological order, but this would require queuing commands, something which I don't think is possible within the discord.py framework. 

The suggested limit of 1 per message also would help reduce the impact.

**Comment by jos-b** [comment]
An issue is that the `FBI open up` reactions are separate from auto-react. I'm thinking that if we have this as a trigger we omit all auto-reactions. Also I'm going to stop auto-reactions from occurring on the `:react` command.
